// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwereiohxjirakkzmxgl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3ZXJlaW9oeGppcmFra3pteGdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MTQxNzUsImV4cCI6MjA2MTE5MDE3NX0.IO59tq81JD8_6FcaU9_JNySVNHyOdARC9JA1vS-LxY8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);