// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gmleizcucueryoamkqxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdtbGVpemN1Y3VlcnlvYW1rcXh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMTU1NzAsImV4cCI6MjA2MDg5MTU3MH0.HXiC9Yrz5mgOWLtf62vgFcQi2UPaE7HKTpmsXMzLgDQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);